# Base image
FROM node:22

RUN corepack enable

WORKDIR /usr/src/app
COPY package*.json ./
RUN pnpm i
COPY . .

RUN pnpm run prisma:generate
RUN pnpm run build:webview
CMD [ "pnpm", "run", "windows:webview" ]

